### ISSUE TITLE
升级时 出现sdcv.el clone失败，源码库已经不存在，是否可以修复下这个问题？

### ISSUE THREAD

**Issue by iT-Boyer** [twlz0ne/multi-translate.el#4]
>  Building multi-translate > Cloning sdcv.el
库源码已经被作者移除：https://github.com/stardiviner/sdcv.el.git
导致 multi-translate 编译失败。

**Comment by twlz0ne** [comment]
https://melpa.org/#/sdcv 还在，不知道发生了什么事。
@stardiviner 能否提供一下仓库的备份，我在 [manateelazycat/sdcv](https://github.com/manateelazycat/sdcv) 没找到 943ae3e90cc9a0a88a37cc710acd7424fd4defc4 这个提交。

**Comment by stardiviner** [comment]
Background here:
https://github.com/melpa/melpa/issues/7872

**Comment by twlz0ne** [comment]
https://github.com/melpa/melpa/issues/7872#issuecomment-1032451991

>     * [x]  sdcv.el: https://repo.or.cz/sdcv.el.git
